# Generated by Django 2.2 on 2020-08-24 08:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0004_auto_20200824_1521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TweetsLike',
            new_name='TweetLike',
        ),
    ]
